### ISSUE TITLE
Make usage of framabag easier

### ISSUE THREAD

**Issue by tcitworld** [wallabag/windows-app-legacy#50]
### Issue details

When using Framabag clicking on login when no informations are set, it crashes.

P.S. : I of course know Framabag is not ready.

### Environment

* app version
* OS: Windows 10

### Steps to reproduce/test case

* Clear data/account
* Click on « I'm a Framabag user »
* Don't type anything in the fields that show up
* Click on login

**Comment by jlnostr** [comment]
I know, it happens because the required credentials (URL, Client ID, Client token) are not set, yet. Maybe I should have had disabled the button for now :D

**Comment by jlnostr** [comment]
Is framabag ready now? And if so, does it have a "shared" client Id/secret? @wallabag/core

**Comment by tcitworld** [comment]
Not at all, the migration script is not yet written. :(

**Comment by jlnostr** [comment]
Okay, just tell me when it's ready :)
